name: Publish Packages

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=1.0.0-stage
    - name: Publish Hydra.Core.Tests
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: Hydra.Core.Tests/Hydra.Core.Tests.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          PACKAGE_NAME: Hydra.Core.Tests
          NUGET_SOURCE: https://api.nuget.org
